sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t xxhashanxx/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true xxhashanxx/docker-react npm run test